// examples/wproofreader-sdk-vue-tinymce/src/components/Editor.vue
<script>
import TinyMCE from "@tinymce/tinymce-vue";
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';

export default {
	setup: () => {
		const text = 'Enter you\'re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';
		const initCallback = (editor) => {
			WProofreaderSDK.init({
				container: editor.iframeElement
			});
		};

		return { text, initCallback };
	},
	components: {
		TinyMCE
	}
};
</script>

<template>
	<TinyMCE
		:initialValue="text"
		:init="{
			init_instance_callback: initCallback
		}"
	/>
</template>

// examples/wproofreader-sdk-react-froala/src/Editor.js
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';
import FroalaEditor from 'react-froala-wysiwyg';

import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

function Editor() {
	const text = 'Enter you\'re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';

	return (
		<FroalaEditor
			tag='textarea'
			model={text}
			config={{
				events : {
					'initialized' : function() {
						WProofreaderSDK.init({
							container: this.$iframe ? this.$iframe[0] : this.el
						});
					}
				}
			}}
		/>
	);
}

export default Editor;
