// examples/wproofreader-sdk-react-froala/src/Editor.js
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';
import FroalaEditor from 'react-froala-wysiwyg';

import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

function Editor() {
	const text = 'Enter you\'re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';

	return (
		<FroalaEditor
			tag='textarea'
			model={text}
			config={{
				events : {
					'initialized' : function() {
						WProofreaderSDK.init({
							container: this.$iframe ? this.$iframe[0] : this.el
						});
					}
				}
			}}
		/>
	);
}

export default Editor;

// examples/wproofreader-sdk-vue-froala/src/components/Editor.vue
<script>
import "froala-editor/css/froala_editor.pkgd.min.css";
import FroalaEditor from "froala-editor/js/froala_editor.pkgd.min.js";
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';

export default {
	setup: () => {
		const text = 'Enter you\'re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';
		return { text };
	},
	mounted: () => {
		new FroalaEditor("#edit", {
			events: {
				initialized() {
					WProofreaderSDK.init({
						container: this.$iframe ? this.$iframe[0] : this.el
					});
				}
			}
		});
	},
};
</script>


<template>
	<div id="edit">{{ text }}</div>
</template>
