// examples/wproofreader-sdk-vue-quill/src/components/Editor.vue
<script>
import '@vueup/vue-quill/dist/vue-quill.snow.css';
import { QuillEditor } from '@vueup/vue-quill'
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';

export default {
	setup: () => {
		const text = 'Enter you\’re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';
		return { text };
	},
	components: {
		QuillEditor
	},
	methods: {
		onReady(editor) {
			WProofreaderSDK.init({
				container: editor.root
			});
		}
	}
};
</script>

<template>
	<QuillEditor theme="snow" v-model:content="text" content-type="text" @ready="onReady"/>
</template>

// examples/wproofreader-sdk-react-quill/src/Editor.js
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import WProofreaderSDK from '@webspellchecker/wproofreader-sdk-js';
import { useRef, useEffect } from 'react';

function Editor() {
	const text = 'Enter you\'re text here with real spelling and grammer mistakes to see how WProofreader work. Alot of potential errors will be underlined; hover on the marked wods for instant correction suggesstions.';
	const quillRef = useRef(null);

	useEffect(() => {
		if (quillRef.current) {
			WProofreaderSDK.init({
				container: quillRef.current.getEditor().root
			});
		}
	}, []);

	return (
		<ReactQuill
			ref={quillRef}
			value={text}
			theme="snow" // You can use other themes if desired
		/>
	);
}

export default Editor;
